#!/bin/env bash
if [[ $1 == get ]]; then
	if [[ $2 == current ]] || [[ -z $2 ]]; then
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	elif [[ $2 == governors ]]; then
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
	fi
elif [[ $1 == set ]]; then
	function setgovernor {
		governor=$1
		if grep -w "$governor" /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors  > /dev/null; then
			echo "$governor" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null
		elif [[ -z "$governor" ]]; then
			echo "no governor specified (use \"governor get governors\" to show governors)"; exit 1
		else
			echo "invalid governor $governor (use \"governor get governors\" to show governors)"; exit 1
		fi
	}
	setgovernor $2
elif [[ -z $1 ]]; then
	echo "no operation specified (use \"governor help\" for help)"; exit 1
elif [[ $1 == help ]]; then
	if [[ $2 == get ]]; then
		echo -e "usage: governor get <option>\noptions: current, governors"
        elif [[ $2 == set ]]; then
		echo -e "usage: governor set <governor>\nuse "governor get governors" to show governors"
	else
	echo -e "usage: governor <operation> <option/governor>\noperations: help, get, set\nuse an operation's name with help to see available options"
	fi
else 
	echo "invalid operation: $1 (use "governor help" for help)"; exit 1
fi
